# -*- coding: utf-8 -*-
"""Deyimler ve anlamları. Her anlam (mümkün olduğunca) benzersizdir."""

IDIOMS = [
    ("etekleri zil çalmak", "çok sevinmek"),
    ("ağzı kulaklarına varmak", "çok sevinip mutlu olmak"),
    ("küplere binmek", "çok öfkelenmek"),
    ("tepesi atmak", "birden öfkelenmek"),
    ("burnundan kıl aldırmamak", "çok aksi ve huysuz olmak"),
    ("kulak asmamak", "söylenenleri dikkate almamak"),
    ("kulak kabartmak", "gizlice dinlemeye çalışmak"),
    ("göz yummak", "bir kusuru görmezden gelmek"),
    ("göze girmek", "beğenilip değer kazanmak"),
    ("gözden düşmek", "değerini, sevgisini yitirmek"),
    ("göz kulak olmak", "korumak, gözetmek"),
    ("dört gözle beklemek", "bir şeyi sabırsızlıkla beklemek"),
    ("eli açık olmak", "cömert olmak"),
    ("eli sıkı olmak", "cimri olmak"),
    ("el atmak", "bir işe girişmek, yardım etmek"),
    ("eli kulağında olmak", "olması çok yakın olmak"),
    ("etekleri tutuşmak", "telaşlanmak, çok acele etmek"),
    ("ayağına dolaşmak", "engel olmak, ayak bağı olmak"),
    ("ayağını denk almak", "dikkatli ve uyanık olmak"),
    ("ayak diremek", "bir konuda ısrar etmek"),
    ("baş başa kalmak", "yalnız kalmak"),
    ("başını ağrıtmak", "gereksiz konuşup rahatsız etmek"),
    ("baştan savmak", "bir işi gelişigüzel, özensiz yapmak"),
    ("başa çıkmak", "bir güçlüğün üstesinden gelmek"),
    ("baş göz etmek", "evlendirmek"),
    ("burun kıvırmak", "küçümsemek, beğenmemek"),
    ("burnu havada olmak", "kibirli, gururlu olmak"),
    ("yüzü gülmek", "sevinmek, mutlu olmak"),
    ("yüz çevirmek", "ilgisini kesmek, küsmek"),
    ("yüz vermek", "ilgi gösterip şımartmak"),
    ("yüreği ağzına gelmek", "çok korkmak ya da heyecanlanmak"),
    ("yüreği yanmak", "büyük bir acı duymak"),
    ("içi içine sığmamak", "sevinçten heyecanlanmak"),
    ("içi rahat etmek", "kaygısı kalmamak, ferahlamak"),
    ("kanı kaynamak", "birini sevmek, ısınmak"),
    ("kafa patlatmak", "bir konu üzerinde çok düşünmek"),
    ("kafası karışmak", "ne yapacağını bilememek"),
    ("aklı başına gelmek", "yanlışını anlayıp doğruya yönelmek"),
    ("aklı almamak", "bir şeyi anlayamamak, kavrayamamak"),
    ("aklına koymak", "bir şeyi yapmaya kesin karar vermek"),
    ("aklından geçirmek", "tasarlamak, düşünmek"),
    ("dilinin ucunda olmak", "hatırlamaya çalışıp bir türlü söyleyememek"),
    ("dile düşmek", "hakkında dedikodu yapılmak"),
    ("ağız birliği etmek", "sözü önceden birleştirmek"),
    ("ağzından bal akmak", "çok tatlı ve etkili konuşmak"),
    ("ağzı laf yapmak", "etkili, ikna edici konuşmak"),
    ("ağzı kulağına varmak", "_skip"),
    ("dört dönmek", "ne yapacağını şaşırmak, telaşlanmak"),
    ("dünyalar onun olmak", "çok sevinmek, çok mutlu olmak"),
    ("havalara uçmak", "çok sevinmek (mutluluktan)"),
    ("burnundan gelmek", "bir mutluluğun ardından üzülmek"),
    ("ağzı açık kalmak", "şaşırıp hayran kalmak"),
    ("parmak ısırmak", "şaşıp kalmak, hayret etmek"),
    ("küçük dilini yutmak", "çok şaşırmak"),
    ("etekleri zil çalar gibi", "_skip"),
    ("eli ayağı buz kesmek", "korkudan ya da heyecandan donakalmak"),
    ("eli ayağına dolaşmak", "telaştan şaşırıp beceriksizleşmek"),
    ("eli boş dönmek", "amacına ulaşamadan geri gelmek"),
    ("elini çabuk tutmak", "acele etmek, hızlı davranmak"),
    ("el bebek gül bebek büyütmek", "çok nazlı, şımartarak büyütmek"),
    ("etekleri kabarmak", "_skip"),
    ("kulağına küpe olmak", "bir olaydan ders çıkarmak"),
    ("kulağı delik olmak", "olup biteni çabuk haber almak"),
    ("burun buruna gelmek", "ansızın karşılaşmak"),
    ("gözü kara olmak", "tehlikeden korkmayan, atılgan olmak"),
    ("gözü açık gitmek", "isteğine ulaşamadan ölmek"),
    ("gözü doymak", "yeterince alıp daha fazlasını istememek"),
    ("gözü dönmek", "öfke ya da hırstan kendini kaybetmek"),
    ("gözden kaçmak", "fark edilmemek, dikkati çekmemek"),
    ("göz gezdirmek", "bir şeye şöyle bir bakmak, incelemek"),
    ("göz hapsine almak", "sürekli izlemek, gözetlemek"),
    ("can kulağıyla dinlemek", "büyük bir dikkatle dinlemek"),
    ("canına minnet bilmek", "bir durumu fırsat sayıp memnun olmak"),
    ("can atmak", "bir şeyi çok istemek"),
    ("cana yakın olmak", "sevimli, sıcakkanlı olmak"),
    ("canı sıkılmak", "üzülmek ya da bunalmak"),
    ("canı çekmek", "bir şeyi yapmayı veya yemeyi istemek"),
    ("çenesi düşmek", "çok ve gereksiz konuşmak"),
    ("çene çalmak", "uzun uzun, boş boş konuşmak"),
    ("dört bir yana koşmak", "_skip"),
    ("dile getirmek", "bir düşünceyi sözle anlatmak"),
    ("diline dolamak", "bir konuyu sürekli tekrarlayıp durmak"),
    ("dişini sıkmak", "zorluğa katlanıp dayanmak"),
    ("dişe dokunur olmak", "önemli, işe yarar olmak"),
    ("etekleri dolu olmak", "_skip"),
    ("kaşla göz arasında", "çok kısa bir sürede, hemen"),
    ("kaş yapayım derken göz çıkarmak", "düzelteyim derken büsbütün bozmak"),
    ("kafa tutmak", "karşı gelmek, başkaldırmak"),
    ("kafadan atmak", "bilmeden, rastgele konuşmak"),
    ("kelle koltukta gezmek", "her an ölümü göze alarak yaşamak"),
    ("kol kanat germek", "korumak, sahip çıkmak"),
    ("kolları sıvamak", "bir işe büyük bir istekle girişmek"),
    ("kulağı kirişte olmak", "bir haberi tetikte bekleyip dinlemek"),
    ("burun şişirmek", "_skip"),
    ("burnunu sokmak", "ilgisi olmayan işe karışmak"),
    ("burnunun dikine gitmek", "öğüt dinlemeyip bildiğini yapmak"),
    ("pabucu dama atılmak", "gözden düşüp önemini yitirmek"),
    ("pabuç bırakmamak", "yılmamak, kolayca boyun eğmemek"),
    ("püf noktası", "bir işin en önemli ve ince yanı"),
    ("pişkinlik etmek", "utanması gereken yerde aldırmaz görünmek"),
    ("pireyi deve yapmak", "küçük bir şeyi büyütmek, abartmak"),
    ("pişmiş aşa su katmak", "yoluna girmiş bir işi bozmak"),
    ("ağzına bir parmak bal çalmak", "tatlı sözlerle oyalamak, avutmak"),
    ("ağzından çıkanı kulağı duymamak", "öfkeyle düşünmeden konuşmak"),
    ("ağız değiştirmek", "söylediğinin tersini söylemeye başlamak"),
    ("tuzu kuru olmak", "sıkıntısı, derdi olmamak"),
    ("turnayı gözünden vurmak", "büyük ve beklenmedik bir kazanç sağlamak"),
    ("ipe un sermek", "bir işi yapmamak için bahane bulmak"),
    ("ipliğini pazara çıkarmak", "kötü yönlerini herkese açığa vurmak"),
    ("iki ayağını bir pabuca sokmak", "birini bir işi çabucak yapmaya zorlamak"),
    ("iğneyle kuyu kazmak", "çok güç bir işi sabırla yapmaya çalışmak"),
    ("incir çekirdeğini doldurmaz", "önemsiz, değersiz olmak"),
    ("çantada keklik saymak", "elde edildiğini kesin gibi düşünmek"),
    ("çam devirmek", "farkında olmadan karşısındakini kıracak söz söylemek"),
    ("çığ gibi büyümek", "gittikçe artıp çoğalmak"),
    ("çorbada tuzu bulunmak", "bir işte küçük de olsa emeği geçmek"),
    ("balık kavağa çıkınca", "hiçbir zaman, asla"),
    ("baltayı taşa vurmak", "farkında olmadan kırıcı, ters bir söz söylemek"),
    ("bardağı taşıran son damla", "sabrı tüketen son olay"),
    ("bam teline basmak", "birini en duyarlı olduğu konuda incitmek"),
    ("battı balık yan gider", "iş nasıl olsa bozuldu, gerisi önemli değil"),
    ("bel bağlamak", "birine ya da bir şeye güvenmek"),
    ("burun kıvırmamak", "_skip"),
    ("damdan düşer gibi konuşmak", "yersiz ve birden, hazırlıksız konuşmak"),
    ("dananın kuyruğu kopmak", "gizli kalan bir işin patlak vermesi"),
    ("dem vurmak", "bir konudan sık sık söz etmek"),
    ("dert yanmak", "sıkıntılarını anlatıp yakınmak"),
    ("dut yemiş bülbüle dönmek", "konuşamaz olmak, susup kalmak"),
    ("el ele vermek", "birlikte, dayanışarak çalışmak"),
    ("etekleri tutuşmuş gibi", "_skip"),
    ("foyası meydana çıkmak", "gizli kötü yanı ortaya çıkmak"),
    ("gemileri yakmak", "geri dönülmeyecek kesin bir karar vermek"),
    ("gözünü budaktan sakınmamak", "hiçbir tehlikeden korkmamak"),
    ("hapı yutmak", "kötü, çıkışsız bir duruma düşmek"),
    ("havadan sudan konuşmak", "önemsiz, gündelik şeylerden söz etmek"),
    ("hava atmak", "gösteriş yapmak, caka satmak"),
    ("ха", "_skip"),
    ("ileri geri konuşmak", "yersiz, kırıcı sözler söylemek"),
    ("invan", "_skip"),
    ("kabak tadı vermek", "tekrarı yüzünden bıkkınlık vermek"),
    ("kafa dengi olmak", "düşünce ve zevkleri birbirine uymak"),
    ("kalıbını basmak", "bir şeye kesinlikle güvence vermek"),
    ("kan ağlamak", "büyük sıkıntı içinde olmak"),
    ("kantarın topuzunu kaçırmak", "ölçüyü kaçırmak, aşırıya gitmek"),
    ("kazan kaldırmak", "topluca başkaldırmak, isyan etmek"),
    ("kafasına koymak", "_skip"),
    ("kestirip atmak", "kesin kararını söyleyip tartışmayı bitirmek"),
    ("kılı kırk yarmak", "çok ince ayrıntısına kadar titiz davranmak"),
    ("kırk yılda bir", "çok seyrek, pek ender"),
    ("kıyıda köşede kalmak", "önemsenmeyip bir kenara itilmek"),
    ("kulağına çalınmak", "bir haberi rastlantıyla duymak"),
    ("küllerinden doğmak", "bittiği sanılırken yeniden güçlenmek"),
    ("laf altında kalmamak", "karşılık vermesini bilmek"),
    ("laf ebesi olmak", "her söze hazır karşılığı olmak"),
    ("leyleği havada görmek", "yerinde durmayıp çok gezmek"),
    ("maydanoz olmak", "gereksiz yere her işe karışmak"),
    ("nalları dikmek", "ölmek (kaba)"),
    ("ocağına düşmek", "yardım istemek için birine sığınmak"),
    ("oldu olacak kırıldı nacak", "iş iyice bozuldu, geri dönüşü kalmadı"),
    ("ortalığı birbirine katmak", "büyük bir karışıklık çıkarmak"),
    ("öküz altında buzağı aramak", "olmayacak yerde kusur, suç aramak"),
    ("paçayı kurtarmak", "güç bir durumdan zorla sıyrılmak"),
    ("palavra atmak", "yalan, abartılı sözler söylemek"),
    ("püskül belası olmak", "_skip"),
    ("renk vermemek", "duygu ve düşüncesini belli etmemek"),
    ("saman altından su yürütmek", "gizlice, sezdirmeden iş çevirmek"),
    ("sırt çevirmek", "yardımını, ilgisini kesmek"),
    ("su koyvermek", "güvenilmez, gevşek davranmak"),
    ("suya sabuna dokunmamak", "kimseyle çekişmeyip tarafsız kalmak"),
    ("surat asmak", "küskün ve dargın bir yüz takınmak"),
    ("tası tarağı toplamak", "bir yerden büsbütün ayrılmak için toparlanmak"),
    ("tahtası eksik olmak", "aklından zoru olmak (kaba)"),
    ("tereyağından kıl çeker gibi", "çok kolayca, hiç zorlanmadan"),
    ("tuttuğunu koparmak", "girişken olup başarmasını bilmek"),
    ("ucuz atlatmak", "büyük bir tehlikeyi hafif zararla geçiştirmek"),
    ("yangına körükle gitmek", "bir anlaşmazlığı daha da kızıştırmak"),
    ("yağ bağlamak", "içi rahatlayıp sevinmek"),
    ("yan çizmek", "bir işten kaçınmak, sıvışmak"),
    ("yelkenleri suya indirmek", "direnmekten vazgeçip yumuşamak"),
    ("yüksekten atmak", "yapamayacağı şeyleri yapacakmış gibi konuşmak"),
    ("yüz göz olmak", "aşırı senli benli olup saygıyı yitirmek"),
    ("zırnık koklatmamak", "hiçbir şey vermemek, cimrilik etmek"),
    ("zılgıt vermek", "azarlayıp gözünü korkutmak"),
    ("zevahiri kurtarmak", "yalnızca görünüşü kurtarmaya çalışmak"),
]
IDIOMS = [p for p in IDIOMS if p[1] != "_skip"]
