# -*- coding: utf-8 -*-
"""Atasözleri ve anlamları."""

PROVERBS = [
    ("Damlaya damlaya göl olur.", "Küçük birikimler zamanla büyük bir bütün oluşturur."),
    ("Sakla samanı, gelir zamanı.", "Şimdi gereksiz görünen şey ileride işe yarayabilir."),
    ("Ağaç yaşken eğilir.", "İnsanlara iyi alışkanlıklar küçük yaşta kazandırılır."),
    ("Bir elin nesi var, iki elin sesi var.", "Birlikten, dayanışmadan güç doğar."),
    ("Son pişmanlık fayda etmez.", "İş işten geçtikten sonra pişman olmanın yararı olmaz."),
    ("Acele işe şeytan karışır.", "Aceleyle yapılan işler genellikle bozuk çıkar."),
    ("Sürçe sürçe yol alınır.", "Yanılarak ve düşerek de olsa ilerlenir."),
    ("İşleyen demir ışıldar.", "Çalışan, kendini geliştiren kişi değer kazanır."),
    ("Bugünün işini yarına bırakma.", "Yapılacak işi ertelemeden zamanında yapmak gerekir."),
    ("Sabreden derviş muradına ermiş.", "Sabırlı olan, sonunda dileğine kavuşur."),
    ("Sabırla koruk helva olur.", "Sabırla beklenince güç işler bile olumlu sonuçlanır."),
    ("Tatlı dil yılanı deliğinden çıkarır.", "Güzel söz, en katı kişiyi bile yumuşatır."),
    ("Ayağını yorganına göre uzat.", "Giderini gelirine göre ayarlamak gerekir."),
    ("Bakarsan bağ, bakmazsan dağ olur.", "İlgilenilen şey gelişir, ilgilenilmeyen bozulur."),
    ("Komşu komşunun külüne muhtaçtır.", "İnsanlar birbirinin yardımına ihtiyaç duyar."),
    ("İğneyi kendine, çuvaldızı başkasına batır.", "Başkasını eleştirmeden önce kendine bakmak gerekir."),
    ("Ne ekersen onu biçersin.", "İnsan yaptığının karşılığını görür."),
    ("Rüzgâr eken fırtına biçer.", "Kötülük yapan, daha büyük kötülükle karşılaşır."),
    ("Gülme komşuna, gelir başına.", "Başkasının başına gelene gülen, aynısıyla karşılaşabilir."),
    ("Bir musibet bin nasihatten iyidir.", "Yaşanan bir kötü olay, binlerce öğütten çok öğretir."),
    ("Görünen köy kılavuz istemez.", "Açık, belli olan şey için açıklamaya gerek yoktur."),
    ("Ateş düştüğü yeri yakar.", "Bir acıyı en çok onu yaşayan duyar."),
    ("Sütten ağzı yanan yoğurdu üfleyerek yer.", "Bir kez zarar gören sonra çok dikkatli olur."),
    ("İt ürür kervan yürür.", "Engellemelere aldırmadan iş sürdürülür."),
    ("Üzüm üzüme baka baka kararır.", "İnsan birlikte olduğu kişilerden etkilenir."),
    ("Körle yatan şaşı kalkar.", "Kötü kişiyle düşüp kalkan ondan zarar görür."),
    ("Bal tutan parmağını yalar.", "İşin içinde olan ondan pay alır."),
    ("Sora sora Bağdat bulunur.", "Sorarak ve araştırarak istenen sonuca varılır."),
    ("Akıl akıldan üstündür.", "Bir kişinin aklına başka birinin aklı katkı sağlar."),
    ("Mum dibine ışık vermez.", "Kişi en yakınına yarar sağlamakta yetersiz kalabilir."),
    ("Taşıma su ile değirmen dönmez.", "Sürekli dışarıdan destekle iş yürümez."),
    ("Ucuz etin yahnisi tatsız olur.", "Ucuz alınan malın çoğu işe yaramaz çıkar."),
    ("Çürük tahta çivi tutmaz.", "Sağlam olmayan şeye güvenilmez."),
    ("Su uyur düşman uyumaz.", "Düşmana karşı her zaman uyanık olmak gerekir."),
    ("Aç tavuk kendini buğday ambarında sanır.", "İnsan ulaşamadığı şeyi düşleyip durur."),
    ("Aç ayı oynamaz.", "Karşılığı, yararı olmadan kimse iş yapmaz."),
    ("Sakınılan göze çöp batar.", "Çok korunan şey yine de zarar görebilir."),
    ("Görünüşe aldanma.", "Bir şeyi yalnız dış görünüşüne bakarak yargılamamalı."),
    ("Dost kara günde belli olur.", "Gerçek dostluk, zor zamanlarda ortaya çıkar."),
    ("Gün doğmadan neler doğar.", "Beklenmedik iyi şeyler her zaman olabilir."),
    ("Kervan yolda düzülür.", "Bir işe başlanır, eksikleri yol boyunca giderilir."),
    ("Çok bilen çok yanılır.", "Kendine fazla güvenen daha çok yanılgıya düşer."),
    ("Bir çiçekle yaz olmaz.", "Tek bir olumlu belirti, sonucun kesinliğini göstermez."),
    ("Denize düşen yılana sarılır.", "Çaresiz kalan kişi her çareye başvurur."),
    ("El elin eşeğini türkü çağırarak arar.", "Başkasının işi insana ağır gelmez, savsaklanır."),
    ("Sürüden ayrılanı kurt kapar.", "Topluluktan ayrılan, tehlikeyle yalnız kalır."),
    ("İki karpuz bir koltuğa sığmaz.", "Birden çok zor iş aynı anda yürütülemez."),
    ("Ağlamayan çocuğa meme vermezler.", "İsteğini dile getirmeyen kimse istediğini elde edemez."),
    ("Besle kargayı, oysun gözünü.", "İyilik ettiğin kişi sana kötülükle karşılık verebilir."),
    ("Minareyi çalan kılıfını hazırlar.", "Büyük bir yanlış yapan, önceden bahanesini de hazırlar."),
    ("Bir fincan kahvenin kırk yıl hatırı vardır.", "Küçük bir iyilik bile uzun süre unutulmaz."),
    ("Misafir umduğunu değil, bulduğunu yer.", "Konuk, ev sahibinin verdiğiyle yetinir."),
    ("Ev alma komşu al.", "Bir yere yerleşirken çevrenin iyiliği evden önemlidir."),
    ("Armut piş ağzıma düş.", "Emek vermeden sonuç bekleyenler için söylenir."),
    ("Korkunun ecele faydası yoktur.", "Korkmak, gelecek kötü sonucu engellemez."),
    ("Keskin sirke küpüne zarar verir.", "Aşırı öfke, en çok öfkelenen kişiye zarar verir."),
    ("Ağzı yanan aşı üfleyerek yer.", "Bir kez yanan, sonra çok temkinli davranır."),
    ("Boş çuval ayakta durmaz.", "Aç ya da güçsüz kişi iş göremez."),
    ("Davulun sesi uzaktan hoş gelir.", "Bir şey uzaktan güzel görünse de yakını öyle olmayabilir."),
    ("Su küçüğün, söz büyüğün.", "Söz hakkı büyüklere, yol verme küçüklere düşer."),
    ("Tok açın hâlinden anlamaz.", "Sıkıntı çekmeyen, çekenin durumunu kavrayamaz."),
    ("İnsan ayağından, at tırnağından belli olur.", "Kişinin değeri davranışlarından anlaşılır."),
    ("Erken kalkan yol alır.", "İşine erken başlayan başarıya daha çabuk ulaşır."),
    ("Lafla peynir gemisi yürümez.", "Yalnız sözle hiçbir iş yapılamaz."),
    ("Çalma elin kapısını, çalarlar kapını.", "Başkasına yaptığın kötülük sana da yapılır."),
    ("Bir deli kuyuya taş atar, kırk akıllı çıkaramaz.", "Düşüncesizce yapılan iş çok kişiyi uğraştırır."),
    ("Sütten çıkmış ak kaşık gibi.", "Suçsuz, tertemiz görünmek için söylenir."),
    ("İşten artmaz dişten artar.", "Birikim, kazançtan çok tutumlulukla olur."),
    ("Kel ölür sırma saçlı olur.", "Ölen kişinin kusurları unutulup övülür."),
    ("Yuvarlanan taş yosun tutmaz.", "Bir yerde durmayan kişi birikim sağlayamaz."),
    ("Horoz ölür, gözü çöplükte kalır.", "İnsan tutkusundan son ana kadar vazgeçemez."),
    ("Balık baştan kokar.", "Bir işteki bozukluk yöneticiden başlar."),
    ("Ağustosta beyni kaynayanın zemheride kazanı kaynar.", "Yazın çalışan kışın rahat eder."),
    ("Sakla samanı bir gün gelir...", "_skip"),
    ("Kurtla ortak olan yaban koyununu bulamaz.", "Kötü ortakla iş yapan zarara uğrar."),
    ("Az veren candan, çok veren maldan.", "Önemli olan verenin gönlüdür, miktarı değil."),
    ("Damdan düşen damdan düşenin hâlini bilir.", "Bir derdi, ancak o derdi yaşayan anlar."),
    ("Ne oldum dememeli, ne olacağım demeli.", "İnsan ulaştığı yerle övünmemeli, geleceği düşünmeli."),
    ("Aç köpek fırın deler.", "İhtiyaç içindeki kişi yapamayacağını sandığı şeyi yapar."),
    ("Açın gözü ekmek teknesinde olur.", "Eksiği olanın aklı hep o eksikte kalır."),
    ("Bir koltuğa iki karpuz...", "_skip"),
    ("Emek olmadan yemek olmaz.", "Çalışmadan, çabalamadan bir şey elde edilmez."),
    ("Ekmeden biçilmez.", "Emek harcamadan ürün alınmaz."),
    ("Çok söyleme arsız edersin, aç koyma hırsız edersin.", "Aşırılık insanı kötü yola sürükler."),
    ("Gönülsüz yenen aş ya karın ağrıtır ya baş.", "İstemeden yapılan iş zararla sonuçlanır."),
    ("Sürçen at bir daha sürçmez.", "İnsan bir yanılgıdan ders alır, yinelemez."),
    ("Taş yerinde ağırdır.", "Kişi bulunduğu, yakıştığı yerde değerlidir."),
    ("Yalancının mumu yatsıya kadar yanar.", "Yalan er geç ortaya çıkar."),
    ("Doğru söyleyeni dokuz köyden kovarlar.", "Gerçeği söyleyen çoğu zaman hoş karşılanmaz."),
    ("Bir ağaçta gül de biter, diken de.", "Aynı kaynaktan iyi de kötü de çıkabilir."),
    ("Üzümünü ye bağını sorma.", "Yararlandığın şeyin ayrıntısını gereksizce araştırma."),
    ("Yere düşmekle cevher sâkıt olmaz.", "Değerli kişi zor durumda da değerini yitirmez."),
    ("Vakit nakittir.", "Zaman, para kadar değerli ve önemlidir."),
    ("İyilik eden iyilik bulur.", "İyilik yapan, karşılığında iyilikle karşılaşır."),
    ("Damsız ev olmaz.", "_skip"),
    ("Çamur at izi kalsın.", "Asılsız da olsa atılan iftira bir iz bırakır."),
    ("Dağ dağa kavuşmaz, insan insana kavuşur.", "İnsanlar bir gün yeniden karşılaşabilir."),
]
PROVERBS = [p for p in PROVERBS if p[1] != "_skip"]
